import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import Header from '@/components/header'
import SessionProvider from '@/components/providers/session-provider'
import { TooltipProvider } from '@/components/ui/tooltip'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SessionProvider>
                    <TooltipProvider>
                        <div className="container m-auto flex h-screen flex-col gap-2 p-4">
                            <Header />
                            {children}
                        </div>
                    </TooltipProvider>
                    <Toaster />
                </SessionProvider>
            </body>
        </html>
    )
}
